server:
  port: 8080
  servlet:
    context-path: /demo/user

application:
  name: "inugami-demo-user"
  groupId: "io.inugami.springboot.demo.user"
  artifactId: "inugami-springboot-demo-user-webapp"
  version: "@project.version@"
  commitId: "@commitId@"
  commitDate: "@commitDate@"
  
  url:
    activeMq: "tcp://localhost:61616"
    datasource: "jdbc:h2:mem:testdb"


endpoints:
  health:
    sensitive: false
management:
  endpoint:
    health:
      show-details: "ALWAYS"

spring:
  activemq:
    broker-url: "failover:(${application.url.activeMq})"
    user: ""
    password: ""
  datasource:
    url: "${application.url.datasource}"
    username: "sa"
    password: "sa"
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: "update"
      mapping:
        physical-strategy: "org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy"
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    path: "/doc/swagger.html"

inugami:
  release:
    note:
      custom:
        css:
          enabled: true
          path: "META-INF/css/demo-custom.css"
      #path: /demo/user/release-note-app/
      artifactName: "inugami-springboot-demo-user-webapp.releases"
  monitoring:
    exception:
      enabled: true
      show:
        detail:
          enabled: true