server:
  port: 8081
application:
  name: "inugami-demo-user-search"
  groupId: "io.inugami.springboot.demo.user.search"
  artifactId: "inugami-springboot-demo-user-search-webapp"
  version: "@project.version@"
  commitId: "@commitId@"
  commitDate: "@commitDate@"

  url:
    activeMq: "tcp://localhost:61616"

endpoints:
  health:
    sensitive: false
management:
  endpoint:
    health:
      show-details: "ALWAYS"

spring:
  activemq:
    broker-url: "failover:(${application.url.activeMq})"
    user: ""
    password: ""

inugami:
  release:
    note:
      artifactName: "inugami-springboot-demo-user-search-webapp.releases"
  monitoring:
    exception:
      enabled: true
      show:
        detail:
          enabled: true